name: mskimm
description: a software developer
meta_description: "mskimm, a software developer"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
logo: false
paginate: 15

baseurl: '/'
aboutmeurl: '/about.html'
emailurl: '/assets/images/email.png'

# Details for the RSS feed generator
url: 'http://www.mskimm.com'
author: 'mskimm'


theme: jekyll-theme-tactile