name: mskimm
description: a software developer.
meta_description: "mskimm, a software developer"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://www.mskimm.com'
author:         'mskimm'
